#! /bin/bash

d=`pwd`/tmp/usr
cd binutils-2.20.1/

cd libiberty
CFLAGS="-g -fPIC" ./configure --prefix="$d"
make -j3
make install
cd ..

cd bfd
CFLAGS="-g -fPIC" ./configure --enable-shared --prefix="$d"
make -j3
gcc -shared -o libbfd-d.so *.o ../libiberty/*.o -lz
#gcc -shared -o libbfd-d.so *.o $d/lib/libiberty.a
make install

cd $d/lib/
ln -s libbfd-2.20.1.20100303.so libbfd-d.so
